#!/bin/bash

##########################################################################
##
## Sets all string-typed fields to non-analyzed via dynamic templates.
##
##########################################################################

curl -XPUT http://localhost:9200/demo-index -d @set-strings-to-non-analyzed.json
